### ISSUE TITLE
Revisions are not working and show at the bottom of the page

### ISSUE THREAD

**Issue by nt1m** [PalmerAL/DocLayer#168]

**Comment by PalmerAL** [comment]
Can't reproduce this in Safari or Firefox. Can you try clearing the cache? Also, are revisions.js and revisions.css loading?

**Comment by nt1m** [comment]
Happened on 2 devices, and yes, I have cleared the cache.
I think they are loading (since the revision button is there) and revisions.css is loading in the style editor.

**Comment by PalmerAL** [comment]
I'm starting to wonder if some of this is network issues between you and cloudflare (this would explain #118 as well). If you go to https://standaert.net/scratchpad/editor/js/revisions.js and https://standaert.net/scratchpad/editor/css/revisions.css, what do you see there? (if you could copy-and-paste into a gist, that would be great).

Also, is there anything enlightening in the console?

At this point, I can't really think of any other possibilities, so if you have an idea about why this might be happening, let me know.
