### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by PalmerAL** [PalmerAL/DocLayer#201]
Dropbox requires that production apps explain what data they collect. I've started working on a document that explains this:

https://standaert.net/scratchpad/view/#/1h3o3wf0mfl9hhc/1437511700767

@nt1m What do you think should be added/changed?

Once #199 is merged, this will be added to the repository, and a link to it will be added to the bottom of the splash page.

**Comment by nt1m** [comment]
Looks fine to me !
Although, I can't understand this sentence : "Cloudflare about how you use the Scratchpad website. "

**Comment by PalmerAL** [comment]
Oh, that's a bug with the document viewer. After "Cloudflare", there should be a link whose text reads "May collect information"

**Comment by PalmerAL** [comment]
b13dd0075dd59a0558643961931689e3de1949f4.

Is there anything else that needs to be changed before I apply for production approval from dropbox?

Preview: https://standaert.net/doclayer/privacy

**Comment by nt1m** [comment]
@PalmerAL I'm not really good with Privacy policies, but this initial draft looks good to me.
